### ISSUE TITLE
Error in WifiLocation.h on linux machine

### ISSUE THREAD

**Issue by kd8bxp** [gmag11/ESPWifiLocation#3]
Line 7 is
#include "arduino.h"

Should be:
#include "Arduino.h"

I don't think this is an issue if you are on a windows machine,  but is for linux boxes.

Just for completeness - Linux Mint 18.2, I3, 6gb, 1tb, Arduino IDE 1.8.4

**Comment by gmag11** [comment]
fixed on https://github.com/gmag11/ESPWifiLocation/commit/d8b00e34ed668a6a7a3a821de03b265d31af1f5a
